apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/<your-user>/simple-api.git
    targetRevision: main
    path: helm/simple-api
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.repository
          value: "<your-dockerhub-user>/simple-api"
        - name: image.tag
          value: "0.1.0"

  destination:
    server: https://kubernetes.default.svc
    namespace: simple-api

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
